/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * SkyCrypt API
 * SkyCrypt API provides Hypixel SkyBlock profile data, player statistics, networth calculations, inventory views, rendered Minecraft item assets, resource pack metadata, emoji data, and source/license information used by SkyCrypt clients.
 * OpenAPI spec version: 3.0
 */
import { customFetch } from "./mutator/custom-instance";
export type ModelsArmorResultStats = { [key: string]: number };

export interface ModelsSourceTab {
  icon?: string;
  name?: string;
}

export interface ModelsStrippedItem {
  Count?: number;
  containsItems?: ModelsStrippedItem[];
  displayInline?: boolean;
  display_name?: string;
  isInactive?: boolean;
  lore?: string[];
  rarity?: string;
  recombobulated?: boolean;
  shiny?: boolean;
  source?: string;
  sourceTab?: ModelsSourceTab;
  texture_pack?: string;
  texture_path?: string;
  wiki?: string;
}

export interface ModelsArmorResult {
  armor?: ModelsStrippedItem[];
  set_name?: string;
  set_rarity?: string;
  stats?: ModelsArmorResultStats;
}

export interface ModelsAttributeShard {
  abilityLevel?: number;
  abilityMaxLevel?: number;
  abilityName?: string;
  capturedTimestamp?: number;
  family?: string[];
  lore?: string[];
  maxSyphon?: number;
  name?: string;
  owned?: number;
  rarity?: string;
  shardId?: string;
  syphoned?: number;
  texture?: string;
}

export interface ModelsAttributeShardsOutput {
  maxSyphoned?: number;
  maxUnlocked?: number;
  shards?: ModelsAttributeShard[];
  syphoned?: number;
  unlocked?: number;
}

export interface ModelsBestRunOutput {
  damage_dealt?: number;
  damage_mitigated?: number;
  deaths?: number;
  dungeon_class?: string;
  elapsed_time?: number;
  grade?: string;
  mobs_killed?: number;
  score_bonus?: number;
  score_exploration?: number;
  score_skill?: number;
  score_speed?: number;
  secrets_found?: number;
  timestamp?: number;
}

export interface ModelsBestiaryMobOutput {
  kills?: number;
  maxKills?: number;
  maxTier?: number;
  name?: string;
  nextTierKills?: number;
  texture?: string;
  tier?: number;
}

export interface ModelsBestiaryCategoryOutput {
  mobs?: ModelsBestiaryMobOutput[];
  mobsMaxed?: number;
  mobsUnlocked?: number;
  name?: string;
  texture?: string;
}

export type ModelsBestiaryOutputCategories = { [key: string]: ModelsBestiaryCategoryOutput };

export interface ModelsBestiaryOutput {
  categories?: ModelsBestiaryOutputCategories;
  familiesCompleted?: number;
  familiesUnlocked?: number;
  familyTiers?: number;
  level?: number;
  maxFamilyTiers?: number;
  maxLevel?: number;
  totalFamilies?: number;
}

export interface ModelsCenterOfTheForest {
  level?: number;
  maxLevel?: number;
}

export interface ModelsSkill {
  level?: number;
  levelCap?: number;
  levelWithProgress?: number;
  maxLevel?: number;
  maxed?: boolean;
  progress?: number;
  texture?: string;
  uncappedLevel?: number;
  unlockableLevelWithProgress?: number;
  xp?: number;
  xpCurrent?: number;
  xpForNext?: number;
}

export type ModelsClassDataClasses = { [key: string]: ModelsSkill };

export interface ModelsClassData {
  classAverage?: number;
  classAverageWithProgress?: number;
  classes?: ModelsClassDataClasses;
  selectedClass?: string;
  totalClassExp?: number;
}

export interface ModelsCollectionCategoryItemAmount {
  amount?: number;
  username?: string;
}

export interface ModelsCollectionCategoryItem {
  amount?: number;
  amounts?: ModelsCollectionCategoryItemAmount[];
  id?: string;
  maxTier?: number;
  name?: string;
  texture?: string;
  tier?: number;
  totalAmount?: number;
}

export interface ModelsCollectionCategory {
  items?: ModelsCollectionCategoryItem[];
  maxTiers?: number;
  name?: string;
  texture?: string;
  totalTiers?: number;
}

export type ModelsCollectionsOutputCategories = { [key: string]: ModelsCollectionCategory };

export interface ModelsCollectionsOutput {
  categories?: ModelsCollectionsOutputCategories;
  maxedCollections?: number;
  totalCollections?: number;
}

export interface ModelsGetMagicalPowerRarities {
  [key: string]: {
    amount?: number;
    magicalPower?: number;
  };
}

export type ModelsGetMagicalPowerOutputHegemony = {
  amount?: number;
  rarity?: string;
};

export interface ModelsGetMagicalPowerOutput {
  abiphone?: number;
  accessories?: number;
  hegemony?: ModelsGetMagicalPowerOutputHegemony;
  rarities?: ModelsGetMagicalPowerRarities;
  riftPrism?: number;
  total?: number;
}

export type ModelsGetMissingAccessoresOutputEnrichments = { [key: string]: number };

export type ModelsGetMissingAccessoresOutputStats = { [key: string]: number };

export interface ModelsGetMissingAccessoresOutput {
  accessories?: ModelsStrippedItem[];
  enrichments?: ModelsGetMissingAccessoresOutputEnrichments;
  magicalPower?: ModelsGetMagicalPowerOutput;
  missing?: ModelsStrippedItem[];
  recombobulated?: number;
  selectedPower?: string;
  stats?: ModelsGetMissingAccessoresOutputStats;
  total?: number;
  totalRecombobulated?: number;
  unique?: number;
  upgrades?: ModelsStrippedItem[];
}

export interface ModelsCrimsonIsleDojoChallenge {
  id?: string;
  name?: string;
  points?: number;
  rank?: string;
  texture?: string;
  time?: number;
}

export interface ModelsCrimsonIsleDojo {
  challenges?: ModelsCrimsonIsleDojoChallenge[];
  totalPoints?: number;
}

export interface ModelsCrimsonIsleFactions {
  barbariansReputation?: number;
  magesReputation?: number;
  selectedFaction?: string;
}

export interface ModelsCrimsonIsleKuudraTier {
  id?: string;
  kills?: number;
  name?: string;
  texture?: string;
}

export interface ModelsCrimsonIsleKuudra {
  tiers?: ModelsCrimsonIsleKuudraTier[];
  totalKills?: number;
}

export interface ModelsCrimsonIsleOutput {
  dojo?: ModelsCrimsonIsleDojo;
  factions?: ModelsCrimsonIsleFactions;
  kuudra?: ModelsCrimsonIsleKuudra;
}

export interface ModelsMostDamageOutput {
  damage?: number;
  type?: string;
}

export interface ModelsDungeonFloorStats {
  best_score?: number;
  fastest_time?: number;
  fastest_time_s?: number;
  fastest_time_s_plus?: number;
  milestone_completions?: number;
  mobs_killed?: number;
  most_damage?: ModelsMostDamageOutput;
  most_healing?: number;
  most_mobs_killed?: number;
  tier_completions?: number;
  times_played?: number;
  watcher_kills?: number;
}

export interface ModelsFormattedDungeonFloor {
  best_run?: ModelsBestRunOutput;
  name?: string;
  stats?: ModelsDungeonFloorStats;
  texture?: string;
}

export interface ModelsSecretsOutput {
  found?: number;
  secretsPerRun?: number;
}

export interface ModelsDungeonStatsOutput {
  bloodMobKills?: number;
  highestFloorBeatenMaster?: number;
  highestFloorBeatenNormal?: number;
  secrets?: ModelsSecretsOutput;
}

export interface ModelsDungeonsOutput {
  catacombs?: ModelsFormattedDungeonFloor[];
  classes?: ModelsClassData;
  level?: ModelsSkill;
  master_catacombs?: ModelsFormattedDungeonFloor[];
  stats?: ModelsDungeonStatsOutput;
}

export type ModelsEquipmentResultStats = { [key: string]: number };

export interface ModelsEquipmentResult {
  equipment?: ModelsStrippedItem[];
  stats?: ModelsEquipmentResultStats;
}

export interface ModelsWeaponsResult {
  highest_priority_weapon?: ModelsStrippedItem;
  weapons?: ModelsStrippedItem[];
}

export interface ModelsGear {
  armor?: ModelsArmorResult;
  equipment?: ModelsEquipmentResult;
  wardrobe?: ModelsStrippedItem[][];
  weapons?: ModelsWeaponsResult;
}

export interface ModelsMinion {
  maxTier?: number;
  name?: string;
  texture?: string;
  tiers?: number[];
}

export interface ModelsMinionCategory {
  maxedMinions?: number;
  maxedTiers?: number;
  minions?: ModelsMinion[];
  texture?: string;
  totalMinions?: number;
  totalTiers?: number;
}

export interface ModelsMinionSlotsOutput {
  bonusSlots?: number;
  current?: number;
  next?: number;
}

export type ModelsMinionsOutputMinions = { [key: string]: ModelsMinionCategory };

export interface ModelsMinionsOutput {
  maxedMinions?: number;
  maxedTiers?: number;
  minions?: ModelsMinionsOutputMinions;
  minionsSlots?: ModelsMinionSlotsOutput;
  totalMinions?: number;
  totalTiers?: number;
}

export type ModelsMiscAuctionsTotalBought = { [key: string]: number };

export type ModelsMiscAuctionsTotalSold = { [key: string]: number };

export interface ModelsMiscAuctions {
  bids?: number;
  created?: number;
  fees?: number;
  gold_earned?: number;
  gold_spent?: number;
  highest_bid?: number;
  no_bids?: number;
  total_bought?: ModelsMiscAuctionsTotalBought;
  total_sold?: ModelsMiscAuctionsTotalSold;
  won?: number;
}

export interface ModelsConsumable {
  amount?: number;
  maxAmount?: number;
  name?: string;
  texture?: string;
}

export interface ModelsMiscDamage {
  highest_critical_damage?: number;
}

export type ModelsMiscDragonsDeaths = { [key: string]: number };

export type ModelsMiscDragonsFastestKill = { [key: string]: number };

export type ModelsMiscDragonsLastHits = { [key: string]: number };

export type ModelsMiscDragonsMostDamage = { [key: string]: number };

export interface ModelsMiscDragons {
  deaths?: ModelsMiscDragonsDeaths;
  ender_crystals_destroyed?: number;
  fastest_kill?: ModelsMiscDragonsFastestKill;
  last_hits?: ModelsMiscDragonsLastHits;
  most_damage?: ModelsMiscDragonsMostDamage;
}

export interface ModelsMiscEndstoneProtector {
  deaths?: number;
  kills?: number;
}

export interface ModelsMiscEssence {
  amount?: number;
  name?: string;
  texture?: string;
}

export interface ModelsMiscGifts {
  given?: number;
  received?: number;
}

export interface ModelsMiscKill {
  amount?: number;
  name?: string;
}

export interface ModelsMiscKills {
  deaths?: ModelsMiscKill[];
  kills?: ModelsMiscKill[];
  total_deaths?: number;
  total_kills?: number;
}

export type ModelsMiscMythologicalEventBurrowsChainsComplete = { [key: string]: number };

export type ModelsMiscMythologicalEventBurrowsDugCombat = { [key: string]: number };

export type ModelsMiscMythologicalEventBurrowsDugNext = { [key: string]: number };

export type ModelsMiscMythologicalEventBurrowsDugTreasure = { [key: string]: number };

export interface ModelsMiscMythologicalEvent {
  burrows_chains_complete?: ModelsMiscMythologicalEventBurrowsChainsComplete;
  burrows_dug_combat?: ModelsMiscMythologicalEventBurrowsDugCombat;
  burrows_dug_next?: ModelsMiscMythologicalEventBurrowsDugNext;
  burrows_dug_treasure?: ModelsMiscMythologicalEventBurrowsDugTreasure;
  kills?: number;
}

export interface ModelsMiscPetMilestone {
  amount?: number;
  progress?: number;
  rarity?: string;
  total?: number;
}

export interface ModelsMiscProfileUpgrades {
  [key: string]: number;
}

export interface ModelsMiscSeasonOfJerry {
  most_cannonballs_hit?: number;
  most_damage_dealt?: number;
  most_magma_damage_dealt?: number;
  most_snowballs_hit?: number;
}

export type ModelsMiscOutputClaimedItems = { [key: string]: number };

export type ModelsMiscOutputPetMilestones = { [key: string]: ModelsMiscPetMilestone };

export type ModelsMiscOutputUncategorized = { [key: string]: unknown };

export interface ModelsMiscOutput {
  auctions?: ModelsMiscAuctions;
  claimed_items?: ModelsMiscOutputClaimedItems;
  consumables?: ModelsConsumable[];
  damage?: ModelsMiscDamage;
  dragons?: ModelsMiscDragons;
  endstone_protector?: ModelsMiscEndstoneProtector;
  essence?: ModelsMiscEssence[];
  gifts?: ModelsMiscGifts;
  kills?: ModelsMiscKills;
  mythological_event?: ModelsMiscMythologicalEvent;
  pet_milestones?: ModelsMiscOutputPetMilestones;
  profile_upgrades?: ModelsMiscProfileUpgrades;
  season_of_jerry?: ModelsMiscSeasonOfJerry;
  uncategorized?: ModelsMiscOutputUncategorized;
}

export type ModelsStrippedPetStats = { [key: string]: number };

export interface ModelsStrippedPet {
  active?: boolean;
  display_name?: string;
  level?: number;
  lore?: string[];
  maxLevel?: number;
  rarity?: string;
  stats?: ModelsStrippedPetStats;
  texture_path?: string;
  type?: string;
}

export interface ModelsPetScoreReward {
  bonus?: number;
  score?: number;
  unlocked?: boolean;
}

export type ModelsPetScoreStats = { [key: string]: number };

export interface ModelsPetScore {
  amount?: number;
  reward?: ModelsPetScoreReward[];
  stats?: ModelsPetScoreStats;
}

export interface ModelsOutputPets {
  amount?: number;
  amountSkins?: number;
  missing?: ModelsStrippedPet[];
  petScore?: ModelsPetScore;
  pets?: ModelsStrippedPet[];
  total?: number;
  totalCandyUsed?: number;
  totalPetExp?: number;
}

export interface ModelsRiftCastleOutput {
  grubberStacks?: number;
  maxBurgers?: number;
}

export interface ModelsRiftEnigmaOutput {
  souls?: number;
  totalSouls?: number;
}

export interface ModelsRiftMotesOutput {
  lifetime?: number;
  orbs?: number;
  purse?: number;
}

export interface ModelsRiftPorhtal {
  name?: string;
  texture?: string;
  unlocked?: boolean;
}

export interface ModelsRiftPortalsOutput {
  porhtals?: ModelsRiftPorhtal[];
  porhtalsFound?: number;
}

export interface ModelsRiftTimecharms {
  name?: string;
  texture?: string;
  unlocked?: boolean;
  unlockedAt?: number;
}

export interface ModelsRiftTimecharmsOutput {
  timecharms?: ModelsRiftTimecharms[];
  timecharmsFound?: number;
}

export interface ModelsRiftOutput {
  armor?: ModelsArmorResult;
  castle?: ModelsRiftCastleOutput;
  enigma?: ModelsRiftEnigmaOutput;
  equipment?: ModelsEquipmentResult;
  motes?: ModelsRiftMotesOutput;
  porhtal?: ModelsRiftPortalsOutput;
  timecharms?: ModelsRiftTimecharmsOutput;
  visits?: number;
}

export interface ModelsEnchantingGame {
  attempts?: number;
  bestScore?: number;
  claims?: number;
  name?: string;
  texture?: string;
}

export interface ModelsEnchantingGameStats {
  bonusClicks?: number;
  games?: ModelsEnchantingGame[];
  lastAttempt?: number;
  lastClaimed?: number;
}

export interface ModelsEnchantingGameData {
  name?: string;
  stats?: ModelsEnchantingGameStats;
}

export type ModelsEnchantingOutputData = { [key: string]: ModelsEnchantingGameData };

export interface ModelsEnchantingOutput {
  data?: ModelsEnchantingOutputData;
  unlocked?: boolean;
}

export type ModelsContestMedals = { [key: string]: number };

export interface ModelsContest {
  amount?: number;
  collected?: number;
  maxed?: boolean;
  medals?: ModelsContestMedals;
  name?: string;
  texture?: string;
}

export interface ModelsMedal {
  amount?: number;
  total?: number;
}

export interface ModelsSkillToolsResult {
  highest_priority_tool?: ModelsStrippedItem;
  tools?: ModelsStrippedItem[];
}

export type ModelsFarmingOutputContests = { [key: string]: ModelsContest };

export type ModelsFarmingOutputMedals = { [key: string]: ModelsMedal };

export interface ModelsFarmingOutput {
  contests?: ModelsFarmingOutputContests;
  contestsAttended?: number;
  copper?: number;
  medals?: ModelsFarmingOutputMedals;
  pelts?: number;
  tools?: ModelsSkillToolsResult;
  uniqueGolds?: number;
}

export interface ModelsKill {
  amount?: number;
  id?: string;
  name?: string;
  texture?: string;
}

export interface ModelsTrophyFishProgress {
  caught?: number;
  tier?: string;
  total?: number;
}

export interface ModelsTrophyFishStage {
  name?: string;
  progress?: ModelsTrophyFishProgress[];
}

export interface ModelsTrophyFish {
  bronze?: number;
  description?: string;
  diamond?: number;
  gold?: number;
  id?: string;
  maxed?: boolean;
  name?: string;
  silver?: number;
  texture?: string;
}

export interface ModelsTrophyFishOutput {
  stage?: ModelsTrophyFishStage;
  totalCaught?: number;
  trophyFish?: ModelsTrophyFish[];
}

export interface ModelsFishingOuput {
  itemsFished?: number;
  lavaSeaCreatures?: ModelsKill[];
  seaCreaturesFished?: number;
  shredderBait?: number;
  shredderFished?: number;
  tools?: ModelsSkillToolsResult;
  treasure?: number;
  treasureLarge?: number;
  trophyFish?: ModelsTrophyFishOutput;
  waterSeaCreatures?: ModelsKill[];
}

export interface ModelsFishFamily {
  collected?: number;
  total?: number;
}

export interface ModelsHinaChapter {
  maxTier?: number;
  tier?: number;
}

export interface SkycrypttypesRodPart {
  donated_museum?: boolean;
  part?: string;
}

export type SkycrypttypesExtraAttributesAttributes = { [key: string]: number };

export type SkycrypttypesExtraAttributesEnchantments = { [key: string]: number };

export type SkycrypttypesExtraAttributesGems = { [key: string]: unknown };

export type SkycrypttypesExtraAttributesRunes = { [key: string]: number };

/**
 * HideFlags       int             `nbt:"HideFlags" json:"HideFlags,omitempty"`
 * Unbreakable     int             `nbt:"Unbreakable" json:"Unbreakable,omitempty"`
 * Enchantments    []Enchantment   `nbt:"ench" json:"ench,omitempty"`
 */
export interface SkycrypttypesExtraAttributes {
  ability_scroll?: string[];
  additional_coins?: number;
  artOfPeaceApplied?: number;
  art_of_war_count?: number;
  attributes?: SkycrypttypesExtraAttributesAttributes;
  auction?: number;
  bid?: number;
  boosters?: string[];
  champion_combat_xp?: number;
  collected_coins?: number;
  compact_blocks?: number;
  divan_powder_coating?: number;
  donated_museum?: boolean;
  drill_part_engine?: string;
  drill_part_fuel_tank?: string;
  drill_part_upgrade_module?: string;
  dungeon_item_level?: unknown;
  dye_item?: string;
  edition?: number;
  enchantments?: SkycrypttypesExtraAttributesEnchantments;
  ethermerge?: number;
  expertise_kills?: number;
  farmed_cultivating?: number;
  farming_for_dummies_count?: number;
  gems?: SkycrypttypesExtraAttributesGems;
  hecatomb_s_runs?: number;
  hook?: SkycrypttypesRodPart;
  hot_potato_count?: number;
  id?: string;
  is_shiny?: boolean;
  item_tier?: number;
  jalapeno_count?: number;
  levelable_overclocks?: number;
  line?: SkycrypttypesRodPart;
  mana_disintegrator_count?: number;
  model?: string;
  modifier?: string;
  new_year_cake_bag_data?: number[];
  new_year_cake_bag_years?: number[];
  new_years_cake?: number;
  party_hat_color?: string;
  party_hat_emoji?: string;
  petInfo?: string;
  pickonimbus_durability?: number;
  polarvoid?: number;
  power_ability_scroll?: string;
  price?: number;
  rarity_upgrades?: number;
  runes?: SkycrypttypesExtraAttributesRunes;
  sack_pss?: number;
  sinker?: SkycrypttypesRodPart;
  skin?: string;
  talisman_enrichment?: string;
  thunder_charge?: number;
  timestamp?: unknown;
  tuned_transmission?: number;
  upgrade_level?: unknown;
  uuid?: string;
  winning_bid?: number;
  wood_singularity_count?: number;
}

export interface SkycrypttypesTexture {
  Signature?: string;
  Value?: string;
}

export interface SkycrypttypesProperties {
  textures?: SkycrypttypesTexture[];
}

export interface SkycrypttypesSkullOwner {
  Id?: string;
  Properties?: SkycrypttypesProperties;
}

export interface SkycrypttypesDisplay {
  Lore?: string[];
  Name?: string;
  color?: number;
}

export interface SkycrypttypesTag {
  ExtraAttributes?: SkycrypttypesExtraAttributes;
  ItemModel?: string;
  SkullOwner?: SkycrypttypesSkullOwner;
  display?: SkycrypttypesDisplay;
}

export interface ModelsProcessedItem {
  Count?: number;
  Damage?: number;
  categories?: string[];
  containsItems?: ModelsProcessedItem[];
  display_name?: string;
  id?: string;
  isInactive?: boolean;
  itemIndex?: number;
  lore?: string[];
  price?: number;
  rarity?: string;
  recombobulated?: boolean;
  shiny?: boolean;
  source?: string;
  tag?: SkycrypttypesTag;
  texture_pack?: string;
  texture_path?: string;
  wiki?: string;
}

export interface ModelsHotfTokens {
  available?: number;
  spent?: number;
  total?: number;
}

export interface ModelsTreeGift {
  maxMilestone?: number;
  milestone?: number;
  texture?: string;
}

export interface ModelsWhispers {
  available?: number;
  spent?: number;
  total?: number;
}

export type ModelsForagingOutputTreeGift = { [key: string]: ModelsTreeGift };

export interface ModelsForagingOutput {
  cotf?: ModelsCenterOfTheForest;
  fishFamily?: ModelsFishFamily;
  foragingLevel?: ModelsSkill;
  hinaChapter?: ModelsHinaChapter;
  hotf?: ModelsProcessedItem[];
  level?: ModelsSkill;
  selectedAxeAbility?: string;
  tokens?: ModelsHotfTokens;
  tools?: ModelsSkillToolsResult;
  treeGift?: ModelsForagingOutputTreeGift;
  whispers?: ModelsWhispers;
}

export interface ModelsCommissions {
  completions?: number;
  milestone?: number;
}

export type ModelsCrystalNucleusRunsCrystals = { [key: string]: string };

export type ModelsCrystalNucleusRunsParts = { [key: string]: string };

export interface ModelsCrystalNucleusRuns {
  crystals?: ModelsCrystalNucleusRunsCrystals;
  parts?: ModelsCrystalNucleusRunsParts;
}

export interface ModelsCrystalHollows {
  crystalHollowsLastAccess?: number;
  nucleusRuns?: number;
  progress?: ModelsCrystalNucleusRuns;
}

export interface ModelsForgeOutput {
  duration?: number;
  endingTime?: number;
  id?: string;
  name?: string;
  slot?: number;
  startingTime?: number;
}

export interface ModelsCorpse {
  amount?: number;
  name?: string;
  texture_path?: string;
}

export interface ModelsCorpses {
  corpses?: ModelsCorpse[];
  found?: number;
  max?: number;
}

export interface ModelsFossil {
  found?: boolean;
  name?: string;
  texture_path?: string;
}

export interface ModelsFossils {
  fossils?: ModelsFossil[];
  found?: number;
  max?: number;
}

export interface ModelsGlaciteTunnels {
  corpses?: ModelsCorpses;
  fossils?: ModelsFossils;
  mineshaftsEntered?: number;
}

export interface ModelsPeakOfTheMountain {
  level?: number;
  max_level?: number;
}

export interface ModelsPowderAmount {
  available?: number;
  spent?: number;
  total?: number;
}

export interface ModelsPowderOutput {
  gemstone?: ModelsPowderAmount;
  glacite?: ModelsPowderAmount;
  mithril?: ModelsPowderAmount;
}

export interface ModelsHotmTokens {
  available?: number;
  spent?: number;
  total?: number;
}

export interface ModelsMiningOutput {
  commissions?: ModelsCommissions;
  crystalHollows?: ModelsCrystalHollows;
  forge?: ModelsForgeOutput[];
  glaciteTunnels?: ModelsGlaciteTunnels;
  hotm?: ModelsProcessedItem[];
  level?: ModelsSkill;
  miningLevel?: ModelsSkill;
  peakOfTheMountain?: ModelsPeakOfTheMountain;
  powder?: ModelsPowderOutput;
  selectedPickaxeAbility?: string;
  tokens?: ModelsHotmTokens;
  tools?: ModelsSkillToolsResult;
}

export interface ModelsSkillsOutput {
  enchanting?: ModelsEnchantingOutput;
  farming?: ModelsFarmingOutput;
  fishing?: ModelsFishingOuput;
  foraging?: ModelsForagingOutput;
  hunting?: ModelsAttributeShardsOutput;
  mining?: ModelsMiningOutput;
}

export interface ModelsSlayerLevel {
  level?: number;
  maxLevel?: number;
  maxed?: boolean;
  xp?: number;
  xpForNext?: number;
}

export type ModelsSlayerDataKills = { [key: string]: number };

export interface ModelsSlayerData {
  kills?: ModelsSlayerDataKills;
  level?: ModelsSlayerLevel;
  name?: string;
  texture?: string;
}

export type ModelsSlayersOutputData = { [key: string]: ModelsSlayerData };

export type ModelsSlayersOutputStats = { [key: string]: number };

export interface ModelsSlayersOutput {
  data?: ModelsSlayersOutputData;
  stats?: ModelsSlayersOutputStats;
  totalSlayerExp?: number;
}

export interface ModelsCombinedOutput {
  accessories?: ModelsGetMissingAccessoresOutput;
  bestiary?: ModelsBestiaryOutput;
  collections?: ModelsCollectionsOutput;
  crimsonIsle?: ModelsCrimsonIsleOutput;
  dungeons?: ModelsDungeonsOutput;
  gear?: ModelsGear;
  minions?: ModelsMinionsOutput;
  misc?: ModelsMiscOutput;
  pets?: ModelsOutputPets;
  rift?: ModelsRiftOutput;
  skills?: ModelsSkillsOutput;
  slayers?: ModelsSlayersOutput;
}

export interface ModelsCropMilestone {
  level?: ModelsSkill;
  name?: string;
  texture?: string;
}

export interface ModelsCropUpgrade {
  level?: ModelsSkill;
  name?: string;
  texture?: string;
}

export interface ModelsDNAAnalysisMilestone {
  level?: number;
  maxLevel?: number;
}

export type ModelsEmbedDataDungeonsClasses = { [key: string]: number };

export interface ModelsEmbedDataDungeons {
  classAverage?: number;
  classes?: ModelsEmbedDataDungeonsClasses;
  dungeoneering?: number;
}

export interface ModelsEmbedNetworth {
  nonCosmetic?: number;
  normal?: number;
}

export interface ModelsRankOutput {
  plusColor?: string;
  plusText?: string;
  rankColor?: string;
  rankText?: string;
}

export type ModelsEmbedDataSkillsSkills = { [key: string]: number };

export interface ModelsEmbedDataSkills {
  skillAverage?: number;
  skills?: ModelsEmbedDataSkillsSkills;
}

export type ModelsEmbedDataSlayersSlayers = { [key: string]: number };

export interface ModelsEmbedDataSlayers {
  slayers?: ModelsEmbedDataSlayersSlayers;
  xp?: number;
}

export interface ModelsEmbedData {
  bank?: number;
  displayName?: string;
  dungeons?: ModelsEmbedDataDungeons;
  game_mode?: string;
  joined?: number;
  networth?: ModelsEmbedNetworth;
  profile_cute_name?: string;
  profile_id?: string;
  purse?: number;
  rank?: ModelsRankOutput;
  skills?: ModelsEmbedDataSkills;
  skyblock_level?: number;
  slayers?: ModelsEmbedDataSlayers;
  username?: string;
  uuid?: string;
}

export type ModelsEmojisResponseEmojisItem = { [key: string]: unknown };

export interface ModelsEmojisResponse {
  emojis?: ModelsEmojisResponseEmojisItem[];
  fetched_at?: number;
}

export interface ModelsFairySouls {
  found?: number;
  total?: number;
}

export type ModelsGardenComposter = { [key: string]: number };

export interface ModelsGardenChip {
  amount?: number;
  maxLevel?: number;
  name?: string;
  texture?: string;
}

export interface ModelsGardenUpgrade {
  level?: number;
  maxLevel?: number;
  name?: string;
  texture?: string;
}

export interface ModelsMutation {
  max?: boolean;
  name?: string;
  texture?: string;
  unlocked?: boolean;
}

export interface ModelsPlotLayout {
  barnSkin?: string;
  layout?: ModelsProcessedItem[];
  total?: number;
  unlocked?: number;
}

export interface ModelsVisitorRarityData {
  completed?: number;
  maxUnique?: number;
  unique?: number;
  visited?: number;
}

export type ModelsVisitorsVisitors = { [key: string]: ModelsVisitorRarityData };

export interface ModelsVisitors {
  completed?: number;
  uniqueVisitors?: number;
  visited?: number;
  visitors?: ModelsVisitorsVisitors;
}

export interface ModelsGarden {
  composter?: ModelsGardenComposter;
  cropMilestones?: ModelsCropMilestone[];
  cropUpgrades?: ModelsCropUpgrade[];
  dnaAnalysisMilestone?: ModelsDNAAnalysisMilestone;
  gardenChips?: ModelsGardenChip[];
  gardenUpgrades?: ModelsGardenUpgrade[];
  level?: ModelsSkill;
  mutations?: ModelsMutation[];
  plot?: ModelsPlotLayout;
  visitors?: ModelsVisitors;
}

export interface ModelsInventory {
  items?: ModelsStrippedItem[];
  name?: string;
  separatorAfter?: number;
  texture?: string;
}

export interface ModelsMemberStats {
  cute_name?: string;
  profile_id?: string;
  removed?: boolean;
  username?: string;
  uuid?: string;
}

export interface SkycryptSrcModelsNetworthType {
  total?: number;
  unsoulboundTotal?: number;
}

export type SkycryptSrcModelsNetworthResultTypes = { [key: string]: SkycryptSrcModelsNetworthType };

export interface SkycryptSrcModelsNetworthResult {
  bank?: number;
  isNonCosmetic?: boolean;
  networth?: number;
  noInventory?: boolean;
  personalBank?: number;
  purse?: number;
  types?: SkycryptSrcModelsNetworthResultTypes;
  unsoulboundNetworth?: number;
}

export interface ModelsNetworth {
  nonCosmetic?: SkycryptSrcModelsNetworthResult;
  normal?: SkycryptSrcModelsNetworthResult;
}

export interface ModelsPlayerResolve {
  displayName?: string;
  username?: string;
  uuid?: string;
}

export interface ModelsProcessingError {
  error?: string;
  message?: string;
  status?: string;
}

export interface ModelsProfilesStats {
  cute_name?: string;
  game_mode?: string;
  profile_id?: string;
  selected?: boolean;
}

export interface ModelsResourcePackConfig {
  author?: string;
  disabled?: boolean;
  icon?: string;
  id?: string;
  name?: string;
  priority?: number;
  url?: string;
  version?: string;
}

export type ModelsSkillsSkills = { [key: string]: ModelsSkill };

export interface ModelsSkills {
  averageSkillLevel?: number;
  averageSkillLevelWithProgress?: number;
  skills?: ModelsSkillsSkills;
  totalSkillXp?: number;
}

export interface ModelsSourceInfo {
  commit?: string;
  license?: string;
  license_spdx?: string;
  name?: string;
  notice?: string;
  repository?: string;
  source?: string;
}

export interface ModelsStatsInfo {
  [key: string]: number;
}

export type ModelsStatsStats = { [key: string]: ModelsStatsInfo };

export interface ModelsStats {
  stats?: ModelsStatsStats;
}

export type ModelsStatsOutputApiSettings = { [key: string]: boolean };

export interface SkycrypttypesSocialMediaLinks {
  DISCORD?: string;
  HYPIXEL?: string;
  TWITCH?: string;
  TWITTER?: string;
}

export interface ModelsStatsOutput {
  apiSettings?: ModelsStatsOutputApiSettings;
  bank?: number;
  displayName?: string;
  fairySouls?: ModelsFairySouls;
  game_mode?: string;
  joined?: number;
  members?: ModelsMemberStats[];
  personalBank?: number;
  profile_cute_name?: string;
  profile_id?: string;
  profiles?: ModelsProfilesStats[];
  purse?: number;
  rank?: ModelsRankOutput;
  selected?: boolean;
  skills?: ModelsSkills;
  skyblock_level?: ModelsSkill;
  social?: SkycrypttypesSocialMediaLinks;
  username?: string;
  uuid?: string;
}

export interface SkycrypttypesItem {
  Count?: number;
  Damage?: number;
  containsItems?: SkycrypttypesItem[];
  id?: number;
  price?: number;
  tag?: SkycrypttypesTag;
}

export type getCombinedProfileStatsResponse200 = {
  data: ModelsCombinedOutput;
  status: 200;
};

export type getCombinedProfileStatsResponse401 = {
  data: ModelsProcessingError;
  status: 401;
};

export type getCombinedProfileStatsResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type getCombinedProfileStatsResponseSuccess = getCombinedProfileStatsResponse200 & {
  headers: Headers;
};
export type getCombinedProfileStatsResponseError = (getCombinedProfileStatsResponse401 | getCombinedProfileStatsResponse500) & {
  headers: Headers;
};

export type getCombinedProfileStatsResponse = getCombinedProfileStatsResponseSuccess | getCombinedProfileStatsResponseError;

export const getGetCombinedProfileStatsUrl = (uuid: string, profileId: string) => {
  return `/api/combined/${uuid}/${profileId}`;
};

/**
 * Returns the combined SkyCrypt payload for a player's SkyBlock profile, including gear, accessories, pets, skills, dungeons, slayers, collections, minions, bestiary, and other profile sections.
 * Resource pack preferences supplied by cookie can affect rendered item texture URLs in the response.
 * @summary Get combined profile data
 */
export const getCombinedProfileStats = async (uuid: string, profileId: string, options?: RequestInit): Promise<getCombinedProfileStatsResponse> => {
  return customFetch<getCombinedProfileStatsResponse>(getGetCombinedProfileStatsUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

export type getSelectedProfileEmbedResponse200 = {
  data: ModelsEmbedData;
  status: 200;
};

export type getSelectedProfileEmbedResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getSelectedProfileEmbedResponse401 = {
  data: ModelsProcessingError;
  status: 401;
};

export type getSelectedProfileEmbedResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type getSelectedProfileEmbedResponseSuccess = getSelectedProfileEmbedResponse200 & {
  headers: Headers;
};
export type getSelectedProfileEmbedResponseError = (getSelectedProfileEmbedResponse400 | getSelectedProfileEmbedResponse401 | getSelectedProfileEmbedResponse500) & {
  headers: Headers;
};

export type getSelectedProfileEmbedResponse = getSelectedProfileEmbedResponseSuccess | getSelectedProfileEmbedResponseError;

export const getGetSelectedProfileEmbedUrl = (uuid: string) => {
  return `/api/embed/${uuid}`;
};

/**
 * Returns compact profile data intended for embeds and previews for a player's selected SkyBlock profile.
 * If Hypixel does not mark a selected profile, the first available profile is used.
 * @summary Get selected profile embed data
 */
export const getSelectedProfileEmbed = async (uuid: string, options?: RequestInit): Promise<getSelectedProfileEmbedResponse> => {
  return customFetch<getSelectedProfileEmbedResponse>(getGetSelectedProfileEmbedUrl(uuid), {
    ...options,
    method: "GET"
  });
};

export type getProfileEmbedResponse200 = {
  data: ModelsEmbedData;
  status: 200;
};

export type getProfileEmbedResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getProfileEmbedResponse401 = {
  data: ModelsProcessingError;
  status: 401;
};

export type getProfileEmbedResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type getProfileEmbedResponseSuccess = getProfileEmbedResponse200 & {
  headers: Headers;
};
export type getProfileEmbedResponseError = (getProfileEmbedResponse400 | getProfileEmbedResponse401 | getProfileEmbedResponse500) & {
  headers: Headers;
};

export type getProfileEmbedResponse = getProfileEmbedResponseSuccess | getProfileEmbedResponseError;

export const getGetProfileEmbedUrl = (uuid: string, profileId: string) => {
  return `/api/embed/${uuid}/${profileId}`;
};

/**
 * Returns compact profile data intended for embeds and previews, including rank, SkyBlock level, skills, dungeons, slayers, purse, bank, and networth summary.
 * The player identifier can be a Minecraft UUID or username. The profile identifier can be a Hypixel profile UUID or profile cute name.
 * @summary Get profile embed data
 */
export const getProfileEmbed = async (uuid: string, profileId: string, options?: RequestInit): Promise<getProfileEmbedResponse> => {
  return customFetch<getProfileEmbedResponse>(getGetProfileEmbedUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

export type listEmojisResponse200 = {
  data: ModelsEmojisResponse;
  status: 200;
};

export type listEmojisResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type listEmojisResponseSuccess = listEmojisResponse200 & {
  headers: Headers;
};
export type listEmojisResponseError = listEmojisResponse500 & {
  headers: Headers;
};

export type listEmojisResponse = listEmojisResponseSuccess | listEmojisResponseError;

export const getListEmojisUrl = () => {
  return `/api/emojis`;
};

/**
 * Returns emoji documents stored by SkyCrypt along with a Unix timestamp indicating when the response was generated.
 * @summary List emojis
 */
export const listEmojis = async (options?: RequestInit): Promise<listEmojisResponse> => {
  return customFetch<listEmojisResponse>(getListEmojisUrl(), {
    ...options,
    method: "GET"
  });
};

export type getGardenStatsResponse200 = {
  data: ModelsGarden;
  status: 200;
};

export type getGardenStatsResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getGardenStatsResponse401 = {
  data: ModelsProcessingError;
  status: 401;
};

export type getGardenStatsResponseSuccess = getGardenStatsResponse200 & {
  headers: Headers;
};
export type getGardenStatsResponseError = (getGardenStatsResponse400 | getGardenStatsResponse401) & {
  headers: Headers;
};

export type getGardenStatsResponse = getGardenStatsResponseSuccess | getGardenStatsResponseError;

export const getGetGardenStatsUrl = (uuid: string, profileId: string) => {
  return `/api/garden/${uuid}/${profileId}`;
};

/**
 * Returns Garden progression, visitors, crop milestones, composter data, plots, upgrades, and related Garden state for a specific SkyBlock profile.
 * @summary Get garden stats
 */
export const getGardenStats = async (uuid: string, profileId: string, options?: RequestInit): Promise<getGardenStatsResponse> => {
  return customFetch<getGardenStatsResponse>(getGetGardenStatsUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

export type renderHeadImageResponse200ApplicationJson = {
  data: unknown;
  status: 200;
};

export type renderHeadImageResponse200ImagePng = {
  data: Blob;
  status: 200;
};

export type renderHeadImageResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type renderHeadImageResponse500 = {
  data: string;
  status: 500;
};

export type renderHeadImageResponseSuccess = (renderHeadImageResponse200ApplicationJson | renderHeadImageResponse200ImagePng) & {
  headers: Headers;
};
export type renderHeadImageResponseError = (renderHeadImageResponse400 | renderHeadImageResponse500) & {
  headers: Headers;
};

export type renderHeadImageResponse = renderHeadImageResponseSuccess | renderHeadImageResponseError;

export const getRenderHeadImageUrl = (textureId: string) => {
  return `/api/head/${textureId}`;
};

/**
 * Renders a Minecraft player head texture as PNG bytes.
 * @summary Render a player head
 */
export const renderHeadImage = async (textureId: string, options?: RequestInit): Promise<renderHeadImageResponse> => {
  return customFetch<renderHeadImageResponse>(getRenderHeadImageUrl(textureId), {
    ...options,
    method: "GET"
  });
};

export type searchProfileInventoryResponse200 = {
  data: ModelsStrippedItem[];
  status: 200;
};

export type searchProfileInventoryResponse401 = {
  data: ModelsProcessingError;
  status: 401;
};

export type searchProfileInventoryResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type searchProfileInventoryResponseSuccess = searchProfileInventoryResponse200 & {
  headers: Headers;
};
export type searchProfileInventoryResponseError = (searchProfileInventoryResponse401 | searchProfileInventoryResponse500) & {
  headers: Headers;
};

export type searchProfileInventoryResponse = searchProfileInventoryResponseSuccess | searchProfileInventoryResponseError;

export const getSearchProfileInventoryUrl = (uuid: string, profileId: string, searchParam: string) => {
  return `/api/inventory/search/${uuid}/${profileId}/${searchParam}`;
};

/**
 * Searches cached inventory tabs for items whose display name or lore contains the search parameter.
 * Call GET /api/inventory/{uuid}/{profileId} first to refresh the short-lived cache for the same player, profile, and resource pack preferences. At most 45 matching items are returned.
 * @summary Search cached profile inventory
 */
export const searchProfileInventory = async (uuid: string, profileId: string, searchParam: string, options?: RequestInit): Promise<searchProfileInventoryResponse> => {
  return customFetch<searchProfileInventoryResponse>(getSearchProfileInventoryUrl(uuid, profileId, searchParam), {
    ...options,
    method: "GET"
  });
};

export type getProfileInventoryResponse200 = {
  data: ModelsInventory[];
  status: 200;
};

export type getProfileInventoryResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getProfileInventoryResponse401 = {
  data: ModelsProcessingError;
  status: 401;
};

export type getProfileInventoryResponseSuccess = getProfileInventoryResponse200 & {
  headers: Headers;
};
export type getProfileInventoryResponseError = (getProfileInventoryResponse400 | getProfileInventoryResponse401) & {
  headers: Headers;
};

export type getProfileInventoryResponse = getProfileInventoryResponseSuccess | getProfileInventoryResponseError;

export const getGetProfileInventoryUrl = (uuid: string, profileId: string) => {
  return `/api/inventory/${uuid}/${profileId}`;
};

/**
 * Returns rendered inventory tabs and stripped item data for a specific SkyBlock profile.
 * This endpoint refreshes the short-lived cache used by the inventory search endpoint. Resource pack preferences supplied by cookie can affect rendered item texture URLs in the response.
 * @summary Get profile inventory
 */
export const getProfileInventory = async (uuid: string, profileId: string, options?: RequestInit): Promise<getProfileInventoryResponse> => {
  return customFetch<getProfileInventoryResponse>(getGetProfileInventoryUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

export type renderItemImageResponse200ApplicationJson = {
  data: unknown;
  status: 200;
};

export type renderItemImageResponse200ImagePng = {
  data: Blob;
  status: 200;
};

export type renderItemImageResponse302 = {
  data: string;
  status: 302;
};

export type renderItemImageResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type renderItemImageResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type renderItemImageResponseSuccess = (renderItemImageResponse200ApplicationJson | renderItemImageResponse200ImagePng) & {
  headers: Headers;
};
export type renderItemImageResponseError = (renderItemImageResponse302 | renderItemImageResponse400 | renderItemImageResponse500) & {
  headers: Headers;
};

export type renderItemImageResponse = renderItemImageResponseSuccess | renderItemImageResponseError;

export const getRenderItemImageUrl = (itemId: string) => {
  return `/api/item/${itemId}`;
};

/**
 * Renders a SkyBlock or Minecraft item as PNG bytes.
 * Resource pack preferences supplied by cookie can affect which texture is rendered. Some renderer results redirect to a canonical asset URL.
 * @summary Render an item
 */
export const renderItemImage = async (itemId: string, options?: RequestInit): Promise<renderItemImageResponse> => {
  return customFetch<renderItemImageResponse>(getRenderItemImageUrl(itemId), {
    ...options,
    method: "GET"
  });
};

export type renderLeatherArmorImageResponse200ApplicationJson = {
  data: unknown;
  status: 200;
};

export type renderLeatherArmorImageResponse200ImagePng = {
  data: Blob;
  status: 200;
};

export type renderLeatherArmorImageResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type renderLeatherArmorImageResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type renderLeatherArmorImageResponseSuccess = (renderLeatherArmorImageResponse200ApplicationJson | renderLeatherArmorImageResponse200ImagePng) & {
  headers: Headers;
};
export type renderLeatherArmorImageResponseError = (renderLeatherArmorImageResponse400 | renderLeatherArmorImageResponse500) & {
  headers: Headers;
};

export type renderLeatherArmorImageResponse = renderLeatherArmorImageResponseSuccess | renderLeatherArmorImageResponseError;

export const getRenderLeatherArmorImageUrl = (type: string, color: string) => {
  return `/api/leather/${type}/${color}`;
};

/**
 * Renders a dyed leather armor piece as PNG bytes for the requested armor piece and color.
 * @summary Render leather armor
 */
export const renderLeatherArmorImage = async (type: string, color: string, options?: RequestInit): Promise<renderLeatherArmorImageResponse> => {
  return customFetch<renderLeatherArmorImageResponse>(getRenderLeatherArmorImageUrl(type, color), {
    ...options,
    method: "GET"
  });
};

export type getProfileNetworthResponse200 = {
  data: ModelsNetworth;
  status: 200;
};

export type getProfileNetworthResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getProfileNetworthResponse401 = {
  data: ModelsProcessingError;
  status: 401;
};

export type getProfileNetworthResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type getProfileNetworthResponseSuccess = getProfileNetworthResponse200 & {
  headers: Headers;
};
export type getProfileNetworthResponseError = (getProfileNetworthResponse400 | getProfileNetworthResponse401 | getProfileNetworthResponse500) & {
  headers: Headers;
};

export type getProfileNetworthResponse = getProfileNetworthResponseSuccess | getProfileNetworthResponseError;

export const getGetProfileNetworthUrl = (uuid: string, profileId: string) => {
  return `/api/networth/${uuid}/${profileId}`;
};

/**
 * Calculates normal and non-cosmetic networth for a player's SkyBlock profile.
 * The player identifier can be a Minecraft UUID or username. The profile identifier can be a Hypixel profile UUID or profile cute name.
 * @summary Get profile networth
 */
export const getProfileNetworth = async (uuid: string, profileId: string, options?: RequestInit): Promise<getProfileNetworthResponse> => {
  return customFetch<getProfileNetworthResponse>(getGetProfileNetworthUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

export type getPlayerStatsResponse200 = {
  data: ModelsStats;
  status: 200;
};

export type getPlayerStatsResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getPlayerStatsResponse401 = {
  data: ModelsProcessingError;
  status: 401;
};

export type getPlayerStatsResponseSuccess = getPlayerStatsResponse200 & {
  headers: Headers;
};
export type getPlayerStatsResponseError = (getPlayerStatsResponse400 | getPlayerStatsResponse401) & {
  headers: Headers;
};

export type getPlayerStatsResponse = getPlayerStatsResponseSuccess | getPlayerStatsResponseError;

export const getGetPlayerStatsUrl = (uuid: string, profileId: string) => {
  return `/api/playerStats/${uuid}/${profileId}`;
};

/**
 * Returns normalized player statistics for a specific SkyBlock profile.
 * The player identifier can be a Minecraft UUID or username. The profile identifier can be a Hypixel profile UUID or profile cute name.
 * @summary Get raw player stats
 */
export const getPlayerStats = async (uuid: string, profileId: string, options?: RequestInit): Promise<getPlayerStatsResponse> => {
  return customFetch<getPlayerStatsResponse>(getGetPlayerStatsUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

export type renderPotionImageResponse200ApplicationJson = {
  data: unknown;
  status: 200;
};

export type renderPotionImageResponse200ImagePng = {
  data: Blob;
  status: 200;
};

export type renderPotionImageResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type renderPotionImageResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type renderPotionImageResponseSuccess = (renderPotionImageResponse200ApplicationJson | renderPotionImageResponse200ImagePng) & {
  headers: Headers;
};
export type renderPotionImageResponseError = (renderPotionImageResponse400 | renderPotionImageResponse500) & {
  headers: Headers;
};

export type renderPotionImageResponse = renderPotionImageResponseSuccess | renderPotionImageResponseError;

export const getRenderPotionImageUrl = (type: string, color: string) => {
  return `/api/potion/${type}/${color}`;
};

/**
 * Renders a potion image for the requested potion type and color.
 * @summary Render a potion
 */
export const renderPotionImage = async (type: string, color: string, options?: RequestInit): Promise<renderPotionImageResponse> => {
  return customFetch<renderPotionImageResponse>(getRenderPotionImageUrl(type, color), {
    ...options,
    method: "GET"
  });
};

export type listResourcePacksResponse200 = {
  data: ModelsResourcePackConfig[];
  status: 200;
};

export type listResourcePacksResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type listResourcePacksResponseSuccess = listResourcePacksResponse200 & {
  headers: Headers;
};
export type listResourcePacksResponseError = listResourcePacksResponse500 & {
  headers: Headers;
};

export type listResourcePacksResponse = listResourcePacksResponseSuccess | listResourcePacksResponseError;

export const getListResourcePacksUrl = () => {
  return `/api/resourcepacks`;
};

/**
 * Returns toggleable resource packs available to SkyCrypt clients.
 * The vanilla resource pack is intentionally omitted because it is the default and cannot be disabled.
 * @summary List resource packs
 */
export const listResourcePacks = async (options?: RequestInit): Promise<listResourcePacksResponse> => {
  return customFetch<listResourcePacksResponse>(getListResourcePacksUrl(), {
    ...options,
    method: "GET"
  });
};

export type getSourceInfoResponse200 = {
  data: ModelsSourceInfo;
  status: 200;
};

export type getSourceInfoResponseSuccess = getSourceInfoResponse200 & {
  headers: Headers;
};
export type getSourceInfoResponse = getSourceInfoResponseSuccess;

export const getGetSourceInfoUrl = () => {
  return `/api/source`;
};

/**
 * Returns repository, license, commit, and notice information for the running SkyCrypt Backend service.
 * @summary Get source information
 */
export const getSourceInfo = async (options?: RequestInit): Promise<getSourceInfoResponse> => {
  return customFetch<getSourceInfoResponse>(getGetSourceInfoUrl(), {
    ...options,
    method: "GET"
  });
};

export type getSelectedProfileStatsResponse200 = {
  data: ModelsStatsOutput;
  status: 200;
};

export type getSelectedProfileStatsResponse401 = {
  data: ModelsProcessingError;
  status: 401;
};

export type getSelectedProfileStatsResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type getSelectedProfileStatsResponseSuccess = getSelectedProfileStatsResponse200 & {
  headers: Headers;
};
export type getSelectedProfileStatsResponseError = (getSelectedProfileStatsResponse401 | getSelectedProfileStatsResponse500) & {
  headers: Headers;
};

export type getSelectedProfileStatsResponse = getSelectedProfileStatsResponseSuccess | getSelectedProfileStatsResponseError;

export const getGetSelectedProfileStatsUrl = (uuid: string) => {
  return `/api/stats/${uuid}`;
};

/**
 * Returns the complete SkyCrypt stats payload for a player's selected SkyBlock profile.
 * If Hypixel does not mark a selected profile, the first available profile is used.
 * @summary Get selected profile stats
 */
export const getSelectedProfileStats = async (uuid: string, options?: RequestInit): Promise<getSelectedProfileStatsResponse> => {
  return customFetch<getSelectedProfileStatsResponse>(getGetSelectedProfileStatsUrl(uuid), {
    ...options,
    method: "GET"
  });
};

export type getProfileStatsResponse200 = {
  data: ModelsStatsOutput;
  status: 200;
};

export type getProfileStatsResponse401 = {
  data: ModelsProcessingError;
  status: 401;
};

export type getProfileStatsResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type getProfileStatsResponseSuccess = getProfileStatsResponse200 & {
  headers: Headers;
};
export type getProfileStatsResponseError = (getProfileStatsResponse401 | getProfileStatsResponse500) & {
  headers: Headers;
};

export type getProfileStatsResponse = getProfileStatsResponseSuccess | getProfileStatsResponseError;

export const getGetProfileStatsUrl = (uuid: string, profileId: string) => {
  return `/api/stats/${uuid}/${profileId}`;
};

/**
 * Returns the complete SkyCrypt stats payload for a player on a specific SkyBlock profile.
 * The player identifier can be a Minecraft UUID or username. The profile identifier can be a Hypixel profile UUID or profile cute name.
 * @summary Get profile stats
 */
export const getProfileStats = async (uuid: string, profileId: string, options?: RequestInit): Promise<getProfileStatsResponse> => {
  return customFetch<getProfileStatsResponse>(getGetProfileStatsUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

export type resolveUsernameByUuidResponse200 = {
  data: ModelsPlayerResolve;
  status: 200;
};

export type resolveUsernameByUuidResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type resolveUsernameByUuidResponseSuccess = resolveUsernameByUuidResponse200 & {
  headers: Headers;
};
export type resolveUsernameByUuidResponseError = resolveUsernameByUuidResponse400 & {
  headers: Headers;
};

export type resolveUsernameByUuidResponse = resolveUsernameByUuidResponseSuccess | resolveUsernameByUuidResponseError;

export const getResolveUsernameByUuidUrl = (uuid: string) => {
  return `/api/username/${uuid}`;
};

/**
 * Resolves a Minecraft UUID to the current username and display name known to SkyCrypt.
 * @summary Resolve username by UUID
 */
export const resolveUsernameByUuid = async (uuid: string, options?: RequestInit): Promise<resolveUsernameByUuidResponse> => {
  return customFetch<resolveUsernameByUuidResponse>(getResolveUsernameByUuidUrl(uuid), {
    ...options,
    method: "GET"
  });
};

export type resolveUuidByUsernameResponse200 = {
  data: ModelsPlayerResolve;
  status: 200;
};

export type resolveUuidByUsernameResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type resolveUuidByUsernameResponse401 = {
  data: ModelsProcessingError;
  status: 401;
};

export type resolveUuidByUsernameResponseSuccess = resolveUuidByUsernameResponse200 & {
  headers: Headers;
};
export type resolveUuidByUsernameResponseError = (resolveUuidByUsernameResponse400 | resolveUuidByUsernameResponse401) & {
  headers: Headers;
};

export type resolveUuidByUsernameResponse = resolveUuidByUsernameResponseSuccess | resolveUuidByUsernameResponseError;

export const getResolveUuidByUsernameUrl = (username: string) => {
  return `/api/uuid/${username}`;
};

/**
 * Resolves a Minecraft username to its UUID and returns the normalized player identity payload.
 * @summary Resolve UUID by username
 */
export const resolveUuidByUsername = async (username: string, options?: RequestInit): Promise<resolveUuidByUsernameResponse> => {
  return customFetch<resolveUuidByUsernameResponse>(getResolveUuidByUsernameUrl(username), {
    ...options,
    method: "GET"
  });
};
