export const MAX_ENCHANTS = new Set([
  "Absorb X",
  "Angler VI",
  "Aqua Affinity I",
  "Bane of Arthropods VII",
  "Big Brain V",
  "Blast Protection VII",
  "Blessing VI",
  "Caster VI",
  "Cayenne V",
  "Champion X",
  "Chance V",
  "Charm V",
  "Cleave VI",
  "Compact X",
  "Corruption V",
  "Counter-Strike V",
  "Critical VII",
  "Cubism VI",
  "Cultivating X",
  "Dedication IV",
  "Delicate V",
  "Depth Strider III",
  "Divine Gift III",
  "Dragon Tracer V",
  "Drain V",
  "Efficiency VI",
  "Efficiency X",
  "Ender Slayer VII",
  "Execute VI",
  "Experience V",
  "Expertise X",
  "Feather Falling X",
  "Feather Falling XX",
  "Ferocious Mana X",
  "Fire Aspect III",
  "Fire Protection VII",
  "First Strike V",
  "Flame II",
  "Forest Pledge V",
  "Fortune IV",
  "Frail VI",
  "Giant Killer VII",
  "Gravity VI",
  "Green Thumb V",
  "Growth VII",
  "Hardened Mana X",
  "Harvesting VI",
  "Hecatomb X",
  "Ice Cold V",
  "Impaling V",
  "Infinite Quiver X",
  "Knockback II",
  "Lapidary V",
  "Lethality VI",
  "Life Steal V",
  "Looting V",
  "Luck of the Sea VII",
  "Luck VII",
  "Lure VI",
  "Magnet VI",
  "Mana Steal III",
  "Mana Vampire X",
  "Overload V",
  "Paleontologist V",
  "Pesterminator VI",
  "Piercing I",
  "Piscary VI",
  "Power VII",
  "Prismatic V",
  "Projectile Protection VII",
  "Prosecute VI",
  "Prosperity V",
  "Protection VII",
  "Punch II",
  "Quantum V",
  "Quick Bite V",
  "Rainbow I",
  "Rainbow II",
  "Rainbow III",
  "Reflection V",
  "Rejuvenate V",
  "Replenish I",
  "Respiration IV",
  "Respite V",
  "Scavenger VI",
  "Scuba VI",
  "Sharpness VII",
  "Silk Touch I",
  "Small Brain V",
  "Smarty Pants V",
  "Smelting Touch I",
  "Smite VII",
  "Smoldering V",
  "Snipe IV",
  "Spiked Hook VI",
  "Stealth I",
  "Strong Mana X",
  "Sugar Rush III",
  "Sunder VI",
  "Tabasco III",
  "Thorns III",
  "Thunderbolt VI",
  "Thunderlord VII",
  "Titan Killer VII",
  "Toxophilite X",
  "Transylvanian V",
  "Triple-Strike V",
  "True Protection I",
  "Turbo-Cacti V",
  "Turbo-Cane V",
  "Turbo-Carrot V",
  "Turbo-Cocoa V",
  "Turbo-Melon V",
  "Turbo-Mushrooms V",
  "Turbo-Potato V",
  "Turbo-Pumpkin V",
  "Turbo-Warts V",
  "Turbo-Wheat V",
  "Woodsplitter VI",
  "Vampirism VI",
  "Venomous VII",
  "Vicious V",
  "Tidal III"
]);
