name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    if: github.event.pull_request.head.repo.fork == false && github.event.pull_request.base.ref == 'prod'
    name: Analyze
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript-typescript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

  checks:
    if: github.event.pull_request.head.repo.fork == true
    uses: ./.github/workflows/checks.yml

  tests:
    if: github.event.pull_request.head.repo.fork == true
    uses: ./.github/workflows/test.yml

  build:
    if: github.event.pull_request.head.repo.fork == true
    uses: ./.github/workflows/build.yml
