name: Test

on:
  workflow_call:

jobs:
  vitest:
    name: Vitest (Server + Browser)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: PNPM Install
        uses: ./.github/actions/pnpm-install

      - name: Make dummy env for types
        run: mv .env.example .env

      - name: Install Playwright Chromium
        run: pnpm exec playwright install chromium --with-deps

      - name: Run Vitest tests
        run: pnpm test

  # e2e tests are not possible in CI due to the need for 1. the golang backend to be running and 2. the backend needing a hypixel api key, which resets every 24 hours. So skip these in CI and only run them locally.
  # e2e:
  #   name: Playwright E2E
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v7

  #     - name: PNPM Install
  #       uses: ./.github/actions/pnpm-install

  #     - name: Make dummy env for types
  #       run: mv .env.example .env

  #     - name: Install Playwright Chromium
  #       run: pnpm exec playwright install chromium --with-deps

  #     - name: Run E2E tests
  #       run: pnpm test:e2e
